### ISSUE TITLE
suggestion:biome discover

### ISSUE THREAD

**Issue by Monster-Zer0** [Globox1997/VillagerQuests#1]
Have the ability to use a discovery of a particular biome as a goal.

**Comment by Globox1997** [comment]
[villagerquests-1.0.1.zip](https://github.com/Globox1997/VillagerQuests/files/7313954/villagerquests-1.0.1.zip)
Thought about it but now I implemented it. Would appreciate if you test it.
You have to unzip the file and I already added info onto the readme

**Comment by Monster-Zer0** [comment]
ok. sorry bout delay. testing now.

**Comment by Monster-Zer0** [comment]
what is the task type for biome discovery?

**Comment by Globox1997** [comment]
"explore" or "travel"

**Comment by Monster-Zer0** [comment]
this is my datapack entry (below). it is still not showing up. but if it's a chance thing, as mentioned in #2 then I may have to keep trying till I find a villager that works.

```
{
    "id": 7,
    "title": "cart test",
    "level": 0,
    "type": "fight",
    "profession": "cartographer",
    "task": [
        "explore",
        "minecraft:plains"
    ],
    "description": "This is a test description for the first quest",
    "experience": 10,
    "reward": [
        "minecraft:stick",
        10,
        "minecraft:bucket",
        1
    ]
}
```

**Comment by Monster-Zer0** [comment]
![image](https://user-images.githubusercontent.com/5826746/137018129-0275e4a9-3092-4952-b910-80450f28d43e.png)

task not showing up. 

this is the json using a custom biome


```
{
    "id": 5,
    "title": "Fourth Test Quest",
    "level": 0,
    "type": "explore",
    "profession": "cartographer",
    "task": [
        "travel",
        "skylore:ak_nights"
    ],
    "description": "This is a test description for the first quest",
    "experience": 10,
    "reward": [
        "minecraft:stick",
        10,
        "minecraft:bucket",
        1
    ]
}
```

**Comment by Globox1997** [comment]
There has to be an integer in the task list right now

**Comment by Globox1997** [comment]
Like this:
```
    "task": [
        "explore",
        "minecraft:plains",
        1
    ]
```
Released the new version

**Comment by Monster-Zer0** [comment]
this works. but it doesn't allow biomes added via datapack for some weird reason. it allows modded biomes.. however.

**Comment by Globox1997** [comment]
At least it works with vanilla biomes, for reference:
`Biomes: [minecraft:ocean, minecraft:plains, minecraft:desert, minecraft:mountains, minecraft:forest, minecraft:taiga, minecraft:swamp, minecraft:river, minecraft:nether_wastes, minecraft:the_end, minecraft:frozen_ocean, minecraft:frozen_river, minecraft:snowy_tundra, minecraft:snowy_mountains, minecraft:mushroom_fields, minecraft:mushroom_field_shore, minecraft:beach, minecraft:desert_hills, minecraft:wooded_hills, minecraft:taiga_hills, minecraft:mountain_edge, minecraft:jungle, minecraft:jungle_hills, minecraft:jungle_edge, minecraft:deep_ocean, minecraft:stone_shore, minecraft:snowy_beach, minecraft:birch_forest, minecraft:birch_forest_hills, minecraft:dark_forest, minecraft:snowy_taiga, minecraft:snowy_taiga_hills, minecraft:giant_tree_taiga, minecraft:giant_tree_taiga_hills, minecraft:wooded_mountains, minecraft:savanna, minecraft:savanna_plateau, minecraft:badlands, minecraft:wooded_badlands_plateau, minecraft:badlands_plateau, minecraft:small_end_islands, minecraft:end_midlands, minecraft:end_highlands, minecraft:end_barrens, minecraft:warm_ocean, minecraft:lukewarm_ocean, minecraft:cold_ocean, minecraft:deep_warm_ocean, minecraft:deep_lukewarm_ocean, minecraft:deep_cold_ocean, minecraft:deep_frozen_ocean, minecraft:the_void, minecraft:sunflower_plains, minecraft:desert_lakes, minecraft:gravelly_mountains, minecraft:flower_forest, minecraft:taiga_mountains, minecraft:swamp_hills, minecraft:ice_spikes, minecraft:modified_jungle, minecraft:modified_jungle_edge, minecraft:tall_birch_forest, minecraft:tall_birch_hills, minecraft:dark_forest_hills, minecraft:snowy_taiga_mountains, minecraft:giant_spruce_taiga, minecraft:giant_spruce_taiga_hills, minecraft:modified_gravelly_mountains, minecraft:shattered_savanna, minecraft:shattered_savanna_plateau,  minecraft:eroded_badlands, minecraft:modified_wooded_badlands_plateau, minecraft:modified_badlands_plateau, minecraft:bamboo_jungle, minecraft:bamboo_jungle_hills, minecraft:soul_sand_valley, minecraft:crimson_forest, minecraft:warped_forest, minecraft:basalt_deltas, minecraft:dripstone_caves, minecraft:lush_caves]`

`Structures [minecraft:pillager_outpost, minecraft:mineshaft, minecraft:mansion, minecraft:jungle_pyramid, minecraft:desert_pyramid, minecraft:igloo, minecraft:ruined_portal, minecraft:shipwreck, minecraft:swamp_hut, minecraft:stronghold, minecraft:monument, minecraft:ocean_ruin, minecraft:fortress, minecraft:endcity, minecraft:buried_treasure, minecraft:village, minecraft:nether_fossil, minecraft:bastion_remnant]`

**Comment by Monster-Zer0** [comment]
yeah, but I wanted to use custom biomes I created in a datapack. it's fine. as long as I have a description and everything.. it works. just doesn't show the task.. with the title.. it is kinda self explanatory.
